### ISSUE TITLE
Seems like iOS version output is broken?

### ISSUE THREAD

**Issue by backmeupplz** [ults-io/mobile-version-bump-action#3]
Outputs a bunch of logs with the version name and code

**Comment by backmeupplz** [comment]
btw, github action `macos-13`, here's the action:

```
name: Build and deploy iOS app
# on: workflow_dispatch
on:
  push:
    branches:
      - fastlane-ios
jobs:
  build-and-deploy-ios-app:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up node and cache yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: yarn
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
          working-directory: ios
      - name: Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: ios/Podfile.lock
      - name: Bump version
        id: bump-version
        uses: ults-io/mobile-version-bump-action@v2
        with:
          ios-project-path: ios
          bump-type: patch
      - name: Install yarn dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Install pods
        run: pod install
        working-directory: ios
      - name: Deploy to App Store
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: beta
          subdirectory: ios
      - name: Discord notification
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_KEY }}
          message: 'iOS app has been deployed to the App Store (${{ steps.bump-version.outputs.ios-version }}, ${{ steps.bump-version.outputs.ios-build-number}})'
```

android works well
